# ---------- Build Stage ----------
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Set legacy OpenSSL for Node 18+
ENV NODE_OPTIONS=--openssl-legacy-provider

# Disable CI strict warnings (optional, if you have React warnings)
ENV CI=false

RUN npm run build

# ---------- Production Stage ----------
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
