FROM node:18-alpine

# Set environment
ENV NODE_ENV=production

# Set working directory
WORKDIR /app

# Copy dependency definitions
COPY package*.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Copy backend source
COPY . .

# Expose backend port
EXPOSE 5000

# Start backend
CMD ["node", "index.js"]
